# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Arnel Dy's Portfolio"
description: "A Pathologist who loves tinkering."
author:      "Arnel Dy"
